### PR TITLE
Improved the method to parse string to fetch question and options

### PR DESCRIPTION
**Pull request by tanujyadav97**
The previous method didn't work if there was no '?' at the end of the question.
The new method works irrespective of the '?'.

Also replaced urllib with urllib2.

### CODE REVIEW

**Comment by sushant10** [comment]
Are you accounting for multiple word options?

**Comment by tanujyadav97** [comment]
Doesn't the 'lines' list contain lines read by tesseract?

**Comment by sushant10** [comment]
You are right, i forgot i used splitlines and not just split.

**Comment by sushant10** [comment]
You should create a git ignore to remove .idea

**Comment by tanujyadav97** [comment]
Can u please remove it after accepting the PR, currently i am traveling.

**Comment by lucytao01** [comment]
How do I clone this request? I want to use this updated version instead of the broken version.

**Comment by tanujyadav97** [comment]
@lucytao01 you have to wait for the request to be merged.

**Comment by whoisoscar** [comment]
Is the latest version stable?

**Pull request merged**
